#!/bin/sh
STORE="${BGIT_STORE:-$PWD/.bgit}"
cat > .cgitrc << EOF
# Appearance
root-title=Bgit
root-desc=Personal git repositories
virtual-root=/
css=/cgit-dark.css
logo=/cgit.png
js=

# Clone URLs
clone-url=ssh://git@\$HTTP_HOST/\$CGIT_REPO_URL

# Features
enable-git-config=1
snapshots=tar.gz tar.bz2 zip
cache-size=1000

# Filters
source-filter=/usr/lib/cgit/filters/syntax-highlighting.py
about-filter=/usr/lib/cgit/filters/about-formatting.sh
# email-filter=lua:/srv/gid/cgit/email-gravatar.lua

# README
readme=:README.md
readme=:README

# Repositories (must be last)
scan-path=$STORE
EOF
exec lighttpd -D -f cgit-lighttpd.conf
