var.confdir = var.CWD

server.modules = ("mod_cgi", "mod_setenv", "mod_rewrite")
server.document-root = var.confdir + "/cgit"
server.port = 8080
server.bind = "0.0.0.0"
mimetype.assign = (".css" => "text/css", ".png" => "image/png", ".ico" => "image/x-icon")
cgi.assign = ("cgit.cgi" => "")
url.rewrite-once = ("^/$" => "/cgit.cgi")
setenv.add-environment = ("CGIT_CONFIG" => var.confdir + "/.cgitrc")
